/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package co.edu.escuelaing.sparkwebserver;

/**
 * Levanta servio WEB
 *
 * @author Yeison Barreto
 */
public class WebPage {

    public String getPage() {
        String html = "<!DOCTYPE html>\n"
                + "<html lang=\"en\">\n"
                + "\n"
                + "<head>\n"
                + "  <meta charset=\"UTF-8\" />\n"
                + "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
                + "  <title>Bono AREP</title>\n"
                + "</head>\n"
                + "\n"
                + "<body>\n"
                + "  <h1>\n"
                + "    Funciones Bono AREP 2023\n"
                + "  </h1>\n"
                + "  <p>\n"
                + "    Las funciones disponibles son Seno, Coseno, verificar si una cadena es un palíndromo y maginitud de un vector real de dos dimensiones.\n"
                + "  </p>\n"
                + "  <h2>Función Seno:</h2>\n"
                + "        <form action=\"/sin\">\n"
                + "            <label for=\"funSin\">Número:</label><br>\n"
                + "            <input type=\"text\" id=\"funSin\" name=\"name\" value=\"90\"><br><br>\n"
                + "            <input type=\"button\" value=\"Submit\" onclick=\"loadGetMsgSin()\">\n"
                + "        </form> \n"
                + "        <div id=\"getrespmsgSin\"></div>\n"
                + "              \n"
                + "              <h2>Función Coseno:</h2>\n"
                + "        <form action=\"/cos\">\n"
                + "            <label for=\"funCos\">Número:</label><br>\n"
                + "            <input type=\"text\" id=\"funCos\" name=\"name\" value=\"60\"><br><br>\n"
                + "            <input type=\"button\" value=\"Submit\" onclick=\"loadGetMsgCos()\">\n"
                + "        </form> \n"
                + "        <div id=\"getrespmsgCos\"></div>\n"
                + "              \n"
                + "              <h2>¿Es palíndromo?</h2>\n"
                + "        <form action=\"/pal\">\n"
                + "            <label for=\"funPal\">Número:</label><br>\n"
                + "            <input type=\"text\" id=\"funPal\" name=\"name\" value=\"hola\"><br><br>\n"
                + "            <input type=\"button\" value=\"Submit\" onclick=\"loadGetMsgPal()\">\n"
                + "        </form> \n"
                + "        <div id=\"getrespmsgPal\"></div>\n"
                + "              \n"
                + "              <h2>Magnitud del vector:</h2>\n"
                + "        <form action=\"/vector\">\n"
                + "            <label for=\"funVector\">Número uno:</label><br>\n"
                + "            <input type=\"text\" id=\"funVector1\" name=\"name\" value=\"6\"><br><br>\n"
                + "              <label for=\"funVector\">Número dos:</label><br>\n"
                + "              <input type=\"text\" id=\"funVector2\" name=\"name\" value=\"23\"><br><br>\n"
                + "            <input type=\"button\" value=\"Submit\" onclick=\"loadGetMsgVector()\">\n"
                + "        </form> \n"
                + "        <div id=\"getrespmsgVector\"></div>\n"
                + "\n"
                + "        <script>\n"
                + "            function loadGetMsgSin() {\n"
                + "                let nameVar = document.getElementById(\"funSin\").value;\n"
                + "                const xhttp = new XMLHttpRequest();\n"
                + "                xhttp.onload = function() {\n"
                + "                    document.getElementById(\"getrespmsgSin\").innerHTML =\n"
                + "                    this.responseText;\n"
                + "                }\n"
                + "                xhttp.open(\"GET\", \"/sin?x=\"+nameVar);\n"
                + "                xhttp.send();\n"
                + "            }\n"
                + "          \n"
                + "          function loadGetMsgCos() {\n"
                + "                let nameVar = document.getElementById(\"funCos\").value;\n"
                + "                const xhttp = new XMLHttpRequest();\n"
                + "                xhttp.onload = function() {\n"
                + "                    document.getElementById(\"getrespmsgCos\").innerHTML =\n"
                + "                    this.responseText;\n"
                + "                }\n"
                + "                xhttp.open(\"GET\", \"/cos?x=\"+nameVar);\n"
                + "                xhttp.send();\n"
                + "            }\n"
                + "          function loadGetMsgPal() {\n"
                + "                let nameVar = document.getElementById(\"funPal\").value;\n"
                + "                const xhttp = new XMLHttpRequest();\n"
                + "                xhttp.onload = function() {\n"
                + "                    document.getElementById(\"getrespmsgPal\").innerHTML =\n"
                + "                    this.responseText;\n"
                + "                }\n"
                + "                xhttp.open(\"GET\", \"/palindrome?s=\"+nameVar);\n"
                + "                xhttp.send();\n"
                + "            }\n"
                + "          function loadGetMsgVector() {\n"
                + "                let nameVar1 = document.getElementById(\"funVector1\").value;\n"
                + "          		let nameVar2 = document.getElementById(\"funVector2\").value;\n"
                + "                const xhttp = new XMLHttpRequest();\n"
                + "                xhttp.onload = function() {\n"
                + "                    document.getElementById(\"getrespmsgVector\").innerHTML =\n"
                + "                    this.responseText;\n"
                + "                }\n"
                + "                xhttp.open(\"GET\", \"/magnitude?x=\"+nameVar1+\"&y=\"+nameVar2);\n"
                + "                xhttp.send();\n"
                + "            }\n"
                + "        </script>\n"
                + "        \n"
                + "</html>";
        return html;
    }

}
